INSERT INTO USUARIO (USERNAME, MAIL, PASSWORD, ROL) 
        VALUES ('admin', 'admin@acoes.com', 'admin', 'ADMINISTRADOR');
INSERT INTO APP.JOVEN (ID_JOVEN, APELLIDOS, DIRECCION, FECHA_NACIMIENTO, LOCALIDAD, NOMBRE, NUMERO_FAMILIARES, SITUACION_ECONOMICA) 
	VALUES (-1, NULL, NULL, NULL, NULL, NULL, NULL, NULL);